pipeline {
//     agent any
    agent {
        node {
            lable 'Linux-Slave'
        }
    }
    stages {
        stage('SVC') {
            steps {
                sh 'echo "Hello jenkins pipeline"'
                sh 'echo "next steps"'
            }
        }
        stage('Build') {
            steps {
                sh 'echo "Start  task Build"'
            }
        }
        stage('Test') {
            steps {
                 sh 'echo "next task test"'
            }
        }
    }
}